language: java
jdk: openjdk11
install: true

services:
  - docker
  - postgresql

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

cache:
  directories:
    - $HOME/.m2

before_script:
  - psql -c 'create database recipe;' -U postgres

script:
  - mvn clean package
  - docker-compose build

notifications:
  email:
    recipients:
      - hardelele@yahoo.com
    on_success: never
    on_failure: always
