language: java
jdk: openjdk11
install: true

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

cache:
  directories:
    - $HOME/.m2

script:
  - docker-compose build
  - docker-compose run test

notifications:
  email:
    recipients:
      - hardelele@yahoo.com
    on_success: never
    on_failure: always
