version: '3'
services:
  postgres:
    container_name: postgresql
    image: postgres:latest
    ports:
      - "5000:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dev2020
  backend:
    container_name: backend
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresql