# Server configuration
server:
  port: 8080
  servlet:
    context-path: /api/v1

# Spring Boot configuration
spring:
  profiles:
    active: dev
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/recipe
    username: postgres
    password: dev2020
    driver-class-name: org.postgresql.Driver
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
  liquibase:
    change-log: classpath:/master.xml
  flyway:
    enabled: false
